### ISSUE TITLE
Módulo Agenda não encontrado

### ISSUE THREAD

**Issue by Felws** [plainspooky/django-agenda_de_eventos#5]
Boa noite!

Estou recebendo o código ModuleNotFoundError: No module named 'Agenda' ao tentar rodar o programa. Já instalei o pacote Agenda, mas ainda assim continua apontando essa exceção. Alguma ideia do que pode estar ocorrendo?

Valeu.

**Comment by plainspooky** [comment]
Oi, você tem a mensagem de erro completa?

**Comment by Felws** [comment]
Traceback (most recent call last):
  File "manage.py", line 15, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\talis\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\talis\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\core\management\__init__.py", line 308, in execute
    settings.INSTALLED_APPS
  File "C:\Users\talis\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\conf\__init__.py", line 56, in __getattr__
    self._setup(name)
  File "C:\Users\talis\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\conf\__init__.py", line 41, in _setup
    self._wrapped = Settings(settings_module)
  File "C:\Users\talis\AppData\Local\Programs\Python\Python38-32\lib\site-packages\django\conf\__init__.py", line 110, in __init__
    mod = importlib.import_module(self.SETTINGS_MODULE)
  File "C:\Users\talis\AppData\Local\Programs\Python\Python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 961, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 973, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'Agenda'

**Comment by plainspooky** [comment]
Poxa, me desculpe, faz um tempo eu coloquei o programa em um diretório próprio mas esqueci de atualizar o README.md, entre os 5 e 6 é necessário ir para o diretório `src` antes de rodar os comandos com o "manage.py".

Obrigado.
